### ISSUE TITLE
Plugin not working: Plugin settings not loading

### ISSUE THREAD

**Issue by jayrsmith** [marcelofinamorvieira/datocms-plugin-alt-text-ai#1]
Hi @marcelofinamorvieira 

I've installed this but there is an error on the plugin page:

The plugin at https://plugins-cdn.datocms.com/datocms-plugin-alt-text-ai@0.3.0/build/index.html is not responding correctly after 20 seconds.

![Screenshot 2024-01-16 at 9 48 26 am](https://github.com/marcelofinamorvieira/datocms-plugin-alt-text-ai/assets/1701419/6c8b6154-ad32-47c5-b53b-82e4d8f3a0ef)

I also can't see the 'Generate Alt Text' buttons below single asset fields. Is there something else I need to do to enable them?

Thanks
Jay

**Comment by marcelofinamorvieira** [comment]
Hello @jayrsmith,

We just shipped a fix for this, you can re-install the plugins new version (0.4.0) right here: https://www.datocms.com/marketplace/plugins/i/datocms-plugin-alt-text-ai 

Thank you for letting us know!

**Comment by jayrsmith** [comment]
Thanks @marcelofinamorvieira . Working now!
